### ISSUE TITLE
Missed pun opportunity

### ISSUE THREAD

**Issue by tylerchilds** [chardane/TicTacToe#1]
### Repo name
*Before:*
~TicTacToe~

*After:*
TicTacGo

### Filename
*Before:*
~tictactoe.go~

*After:*
tictac.go

**Comment by chardane** [comment]
Ahahahahahahahah perfect! man why didn’t I think about this 😂

**Comment by tylerchilds** [comment]
When you upgrade to the next version, it can be TicTacDos

**Comment by tylerchilds** [comment]
wontfix
